### ISSUE TITLE
Unable to change hair style in character preferences menu.

### ISSUE THREAD

**Issue by TheUSSWatercooler** [JasmineRickards/TGMC-PVE#104]
### Description

Expected: Click hair style button, see list of hair styles.
Result: Click hair style button, nothing happens.

### Test Merges

N/A

### Reproduction Steps

1. Open character preferences, whether in or out of round.
2. Go to character you wish to change hair style on.
3. Click hair style button.
Optional: Spam the button and trigger anti-spam.
4. Nothing happens.

**Comment by thenoob699** [comment]
Sorry for the late reply.
Have you tried hanging your race into another one and then reverting back to the race you wanted to play?
I had this problem with changing the hair color and it was fixed when I changed my race to human.

**Comment by TheUSSWatercooler** [comment]
I'll have to try that when I'm able to hop onto the server again.

**Comment by 567Turtle** [comment]
Yeah, this is a base TGMC thing that's still a problem. It's easy to fix though. Just swap your race to robot, then back to human, and boom, you can change your hairstyle.
